# Generated by Django 3.2.6 on 2021-09-26 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analizer', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcmodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='master.project'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='ifcModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='analizer.ifcmodel'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='analizer.elemento'),
        ),
    ]
