# Generated by Django 3.2.6 on 2021-10-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcmodel',
            name='application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ifcmodel',
            name='schema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
