# Generated by Django 3.2.6 on 2021-10-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analizer', '0003_auto_20211016_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ifcModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analizer.ifcmodel')),
            ],
        ),
    ]
